### PR TITLE
Huge restructure

### PR DESCRIPTION
**Pull request by joshuag1000**
Ok so I have done a massive restructure of the code... It took a while. Nothing has changed only how the code is stored and how different things are called. The restructure allows for the program to work fine without tkinter without a GUI. 
The restructure also allows possible easier expansion of the code. The restructure splits the code into 4 python files: 
**pico_project.py** - This is the start file (Like normal) this is where the program enters and receives any parameters.
**pico_project_generation.py** - This file was needed when ripped the GUI from the main file to prevent import loops and incomplete import errors.
**pico_project_settings.py** - in here are all the variables that are needed by all of the other files in the project. I also put things like the code fragments and lists to make them easy to find when adding more. Again, this was needed so the main 2 files pico_project and pico_project_gui can access all the variables needed.
**pico_project_gui.py** - This contains ALL code needed for the gui. If the user wanted to they could drop this file entirely and the project would/should work fine without a GUI.
If you decide to merge this code, I would highly recommend testing my code and double checking it before merging it with the master.
The code also is not the neatest, but I have tried my best!
I really hope this helps at least a little!
Once again i have done some testing on both windows (normal python install with tkinter) and WSL with the tkinter module uninstalled.

### CODE REVIEW

**Comment by joshuag1000** [comment]
Once again i highly recommend double checking my work here!

**Comment by alphathegeek** [comment]
since it's a re-write, you might want to regress the following, since I noticed it failed:

-try setting run_from_ram : should fail with undefined projectName -- see my patch
-console options should be renamed "features" to be more consistent with output from picotool
-features should be renamed libraries - again, just a usability issue

-try setting any of the advanced options, it should fail with an undefined, I don't have a patch for this.

**Comment by joshuag1000** [comment]
I will merge those changes when I get the time later!

**Comment by joshuag1000** [comment]
I have updated this to now have all of the latest bug fixes.

**Comment by JamesH65** [comment]
Sorry about delay on this, lots of small things to do. Will need to be rebased die to the other changes.

**Comment by joshuag1000** [comment]
I am going to close this request becuase i no longer feel that it is necessary to keep/implement,
Plus it is going to be alot of work to maintain.

**Pull request closed without merging**
