### PR TITLE
Add checkbox to build for Pi Pico W

### PR DESCRIPTION
**Pull request by ThadHouse**
With the Pi Pico, it'd be nice to be able to generate projects with the correct board flag to build for the Pi Pico. This adds a new command line option and a new checkbox in the GUI to generate a Pi Pico W project.

### CODE REVIEW

**Comment by JamesH65** [comment]
I'm currently doing a major rewrite of this area in the PPG, which will allow specifying multiple board types, I hope to push it to a testing branch in the next couple of days. UI should make this PR unnecessary, but, thanks for it anyway!

**Comment by lurch** [comment]
I agree that it'd be nicer to have a generic "board type" option, rather than a boolean "is this Pico or Pico W" option :+1:

**Comment by JamesH65** [comment]
I'll upload the working branch tomorrow - it has a board selection option, with the list obtained from the boards folder in the SDK.

**Comment by JamesH65** [comment]
The PicoW branch is here https://github.com/raspberrypi/pico-project-generator/tree/pico-w-support

Needs testing if anyone has time! Only tested on Lubuntu, not on Win or Mac yet.

**Comment by lurch** [comment]
Haven't done any testing, but left some comments based on a very quick scan of the changes in https://github.com/raspberrypi/pico-project-generator/commit/d2e62dbd19f977330f829fcd49ba53b807f8fd82

**Comment by JamesH65** [comment]
Closing as the other branch has been merged.

**Pull request closed without merging**
